"""
Django settings for wallcraft_ai project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security
SECRET_KEY = 'django-insecure-idg+c3%amqk=74%4+-#8e^*d6cs^$yb2)66$sludjh*$8lcedp'

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project App
    'generator',
]


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'wallcraft_ai.urls'


# Templates Configuration

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


WSGI_APPLICATION = 'wallcraft_ai.wsgi.application'

ASGI_APPLICATION = 'wallcraft_ai.asgi.application'


# Database

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }
}



# Password Validation

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]



# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



# Static Files (CSS, JS, Images)

STATIC_URL = '/static/'


STATICFILES_DIRS = [

    BASE_DIR / 'static',

]



# Media Files (Generated AI Images)

MEDIA_URL = '/media/'


MEDIA_ROOT = BASE_DIR / 'media'




# Default Primary Key

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os

# The URL prefix for serving media files
MEDIA_URL = '/media/'

# The absolute filesystem path to the directory that will hold user-uploaded/generated files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
